pipeline:
  # npm_auth:
  #   image: robertstettner/drone-npm-auth
  #   secrets: [ npm_name, npm_pass, npm_email ]

  build:
    image: node:latest
    commands:
      - npm config set registry https://registry.npm.taobao.org  
      - npm install
      - echo 'test'
      - npm run lib
      - echo $$DOCKER_PASS
      - echo $$NPM_PASSWORD
      - echo $$NPM_CONFIG_PASSWORD
    secrets: [ docker_pass, npm_password]
  publish:
    image: plugins/npm
    secrets: [ npm_username, npm_password,npm_email ]
    username:  ${NPM_USERNAME}
    password: ${NPM_PASSWORD}
    email: ${NPM_EMAIL}
    when:
      branch: master

  telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    token: ${TELEGRAM_TOKEN}
    to: ${TELEGRAM_TO}
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}

  # npm_auth:
      # image: robertstettner/drone-npm-auth
      # secrets: [ npm_username, npm_password, npm_email ]

  # npm:
  #   image: plugins/npm
  #   secrets: [docker_pass]
  #   username: zhengjianwen
  #   password: $$DOCKER_PASS
  #   email: zhengjianwen@outlook.com