pipeline:
  # npm_auth:
  #   image: robertstettner/drone-npm-auth
  #   secrets: [ ${DOCKER_NAME}, ${DOCKER_PASS}, ${DOCKER_EMAIL} ]

  build:
    image: node:latest
    commands:
      - npm config set registry https://registry.npm.taobao.org  
      - npm install
      - echo 'test'
      - npm run lib
      - echo $$DOCKER_PASS
    secrets: [ docker_pass]
  publish:
    image: plugins/npm
    username: ${DOCKER_NAME}
    password: ${DOCKER_PASS}
    email: ${DOCKER_EMAIL}
    when:
      branch: master

  # npm_auth:
      # image: robertstettner/drone-npm-auth
      # secrets: [ npm_username, npm_password, npm_email ]

  # npm:
  #   image: plugins/npm
  #   secrets: [docker_pass]
  #   username: zhengjianwen
  #   password: $$DOCKER_PASS
  #   email: zhengjianwen@outlook.com