pipeline:
  build:
    image: node:latest
    commands:
      - npm config set registry https://registry.npm.taobao.org  
      - npm install
      - echo 'test'
      - npm run lib
      - echo $$DOCKER_PASS
      - echo $$NPM_PASSWORD
      - echo $$NPM_CONFIG_PASSWORD
    secrets: [ docker_pass, npm_password]

  publish:
    image: plugins/npm
    secrets: [ npm_username, npm_password,npm_email ]
    username:  ${NPM_USERNAME}
    password: ${NPM_PASSWORD}
    email: ${NPM_EMAIL}
    when:
      branch: master

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    webhook: ${SLACK_WEBHOOK}
    channel: allshare
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
        {{repo.owner}}/{{repo.name}}第{{build.number}}次构建成功！
      {{else}}
        build {{build.number}} failed. Fix me please.
        {{repo.owner}}/{{repo.name}}第{{build.number}}次构建失败了，快来修理下吧。
      {{/success}}
