pipeline:
  # npm_auth:
  #   image: robertstettner/drone-npm-auth
  #   secrets: [ npm_name, npm_pass, npm_email ]

  build:
    image: node:latest
    commands:
      - npm config set registry https://registry.npm.taobao.org  
      - npm install
      - echo 'test'
      - npm run lib
      - echo $$DOCKER_PASS
      - echo $$npm_name
    secrets: [ docker_pass, npm_name]
  publish:
    image: plugins/npm
    username:  ${NPM_USERNAME}
    password: $$NPM_PASSWORD
    email: zhengjianwen@outlook.com
    when:
      branch: master

  # npm_auth:
      # image: robertstettner/drone-npm-auth
      # secrets: [ npm_username, npm_password, npm_email ]

  # npm:
  #   image: plugins/npm
  #   secrets: [docker_pass]
  #   username: zhengjianwen
  #   password: $$DOCKER_PASS
  #   email: zhengjianwen@outlook.com