pipeline:
  build:
    image: node:latest
    commands:
      - npm config set registry https://registry.npm.taobao.org  
      - npm install
      - echo 'test'
      - npm run lib

  npm:
    image: plugins/npm
    username: zhengjianwen
    password: meiyoumimanpm
    email: zhengjianwen@outlook.com